syntax = "proto3";
package system_state;

option go_package = "nfxvault/protos/gen/system/system_state;systemstatepb";

import "google/protobuf/timestamp.proto";

message SystemState {
  string id = 1;
  bool initialized = 2;
  optional google.protobuf.Timestamp initialized_at = 3;
  optional string initialization_version = 4;
  int32 reset_count = 5;
}

message GetLatestSystemStateRequest {}

message GetLatestSystemStateResponse {
  SystemState system_state = 1;
}

message InitializeSystemRequest {
  string version = 1;
}

message InitializeSystemResponse {
  SystemState system_state = 1;
}

service SystemStateService {
  rpc GetLatestSystemState (GetLatestSystemStateRequest) returns (GetLatestSystemStateResponse);
  rpc InitializeSystem (InitializeSystemRequest) returns (InitializeSystemResponse);
}
