// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"
	"uuid"

	"gorm.io/datatypes"
)

type Tlscertificatesactiveview struct {
	ID               *uuid.UUID      `gorm:"column:id;->"`
	AccountID        *uuid.UUID      `gorm:"column:account_id;->"`
	ProfileID        *uuid.UUID      `gorm:"column:profile_id;->"`
	Domain           *string         `gorm:"column:domain;->"`
	FolderName       *string         `gorm:"column:folder_name;->"`
	Status           *string         `gorm:"column:status;->"`
	Email            *string         `gorm:"column:email;->"`
	Certificate      *string         `gorm:"column:certificate;->"`
	PrivateKey       *string         `gorm:"column:private_key;->"`
	Sans             *datatypes.JSON `gorm:"column:sans;->"`
	Issuer           *string         `gorm:"column:issuer;->"`
	NotBefore        *time.Time      `gorm:"column:not_before;->"`
	NotAfter         *time.Time      `gorm:"column:not_after;->"`
	IsValid          *bool           `gorm:"column:is_valid;->"`
	DaysRemaining    *int            `gorm:"column:days_remaining;->"`
	SansChanged      *bool           `gorm:"column:sans_changed;->"`
	LastErrorMessage *string         `gorm:"column:last_error_message;->"`
	LastErrorTime    *time.Time      `gorm:"column:last_error_time;->"`
	CreatedAt        *time.Time      `gorm:"column:created_at;->"`
	UpdatedAt        *time.Time      `gorm:"column:updated_at;->"`
}

func (Tlscertificatesactiveview) TableName() string { return "vault.TlsCertificatesActiveView" }

var TlscertificatesactiveviewCols = struct {
	ID, AccountID, ProfileID, Domain, FolderName, Status, Email,
	Certificate, PrivateKey, Sans, Issuer, NotBefore, NotAfter, IsValid,
	DaysRemaining, SansChanged, LastErrorMessage, LastErrorTime, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	ProfileID:        "profile_id",
	Domain:           "domain",
	FolderName:       "folder_name",
	Status:           "status",
	Email:            "email",
	Certificate:      "certificate",
	PrivateKey:       "private_key",
	Sans:             "sans",
	Issuer:           "issuer",
	NotBefore:        "not_before",
	NotAfter:         "not_after",
	IsValid:          "is_valid",
	DaysRemaining:    "days_remaining",
	SansChanged:      "sans_changed",
	LastErrorMessage: "last_error_message",
	LastErrorTime:    "last_error_time",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}
