// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type Namecheapddnshostsactiveview struct {
	ID               *uuid.UUID `gorm:"column:id;->"`
	AccountID        *uuid.UUID `gorm:"column:account_id;->"`
	ProfileID        *uuid.UUID `gorm:"column:profile_id;->"`
	CredentialID     *uuid.UUID `gorm:"column:credential_id;->"`
	Domain           *string    `gorm:"column:domain;->"`
	Host             *string    `gorm:"column:host;->"`
	DdnsPassword     *string    `gorm:"column:ddns_password;->"`
	LastIpv4         *string    `gorm:"column:last_ipv4;->"`
	LastSyncedAt     *time.Time `gorm:"column:last_synced_at;->"`
	LastErrorMessage *string    `gorm:"column:last_error_message;->"`
	CreatedAt        *time.Time `gorm:"column:created_at;->"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;->"`
}

func (Namecheapddnshostsactiveview) TableName() string { return "dns.NamecheapDdnsHostsActiveView" }

var NamecheapddnshostsactiveviewCols = struct {
	ID, AccountID, ProfileID, CredentialID, Domain, Host, DdnsPassword,
	LastIpv4, LastSyncedAt, LastErrorMessage, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	ProfileID:        "profile_id",
	CredentialID:     "credential_id",
	Domain:           "domain",
	Host:             "host",
	DdnsPassword:     "ddns_password",
	LastIpv4:         "last_ipv4",
	LastSyncedAt:     "last_synced_at",
	LastErrorMessage: "last_error_message",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}
