// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type Namecheapcredentialsactiveview struct {
	ID               *uuid.UUID `gorm:"column:id;->"`
	AccountID        *uuid.UUID `gorm:"column:account_id;->"`
	ProfileID        *uuid.UUID `gorm:"column:profile_id;->"`
	APIUser          *string    `gorm:"column:api_user;->"`
	UserName         *string    `gorm:"column:user_name;->"`
	APIKey           *string    `gorm:"column:api_key;->"`
	ClientIP         *string    `gorm:"column:client_ip;->"`
	Sandbox          *bool      `gorm:"column:sandbox;->"`
	LastVerifiedAt   *time.Time `gorm:"column:last_verified_at;->"`
	LastErrorMessage *string    `gorm:"column:last_error_message;->"`
	CreatedAt        *time.Time `gorm:"column:created_at;->"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;->"`
}

func (Namecheapcredentialsactiveview) TableName() string { return "dns.NamecheapCredentialsActiveView" }

var NamecheapcredentialsactiveviewCols = struct {
	ID, AccountID, ProfileID, APIUser, UserName, APIKey, ClientIP,
	Sandbox, LastVerifiedAt, LastErrorMessage, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	ProfileID:        "profile_id",
	APIUser:          "api_user",
	UserName:         "user_name",
	APIKey:           "api_key",
	ClientIP:         "client_ip",
	Sandbox:          "sandbox",
	LastVerifiedAt:   "last_verified_at",
	LastErrorMessage: "last_error_message",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}
