// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type NamecheapDdnsHost struct {
	ID               uuid.UUID  `gorm:"type:uuid;primaryKey"`
	AccountID        uuid.UUID  `gorm:"type:uuid;index:idx_namecheap_ddns_hosts_account_id;uniqueIndex:uq_namecheap_ddns_hosts_account_domain_host,priority:1"`
	ProfileID        *uuid.UUID `gorm:"type:uuid"`
	CredentialID     *uuid.UUID `gorm:"type:uuid"`
	Domain           string     `gorm:"type:varchar(255);uniqueIndex:uq_namecheap_ddns_hosts_account_domain_host,priority:2"`
	Host             string     `gorm:"type:varchar(255);uniqueIndex:uq_namecheap_ddns_hosts_account_domain_host,priority:3"`
	DdnsPassword     string     `gorm:"type:text"`
	LastIpv4         *string    `gorm:"type:varchar(45)"`
	LastSyncedAt     *time.Time `gorm:"type:timestamp"`
	LastErrorMessage *string    `gorm:"type:text"`
	CreatedAt        time.Time  `gorm:"autoCreateTime"`
	UpdatedAt        time.Time  `gorm:"autoUpdateTime"`
}

func (NamecheapDdnsHost) TableName() string { return "dns.namecheap_ddns_hosts" }

func (m *NamecheapDdnsHost) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var NamecheapDdnsHostCols = struct {
	ID, AccountID, ProfileID, CredentialID, Domain, Host, DdnsPassword,
	LastIpv4, LastSyncedAt, LastErrorMessage, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	ProfileID:        "profile_id",
	CredentialID:     "credential_id",
	Domain:           "domain",
	Host:             "host",
	DdnsPassword:     "ddns_password",
	LastIpv4:         "last_ipv4",
	LastSyncedAt:     "last_synced_at",
	LastErrorMessage: "last_error_message",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

const (
	NamecheapDdnsHostPk                  = "namecheap_ddns_hosts_pkey"
	NamecheapDdnsHostUkAccountDomainHost = "uq_namecheap_ddns_hosts_account_domain_host"
	NamecheapDdnsHostFkCredential        = "fk_namecheap_ddns_hosts_credential"
)
