// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type TlsCertificate struct {
	ID               uuid.UUID       `gorm:"type:uuid;primaryKey"`
	AccountID        *uuid.UUID      `gorm:"type:uuid"`
	ProfileID        *uuid.UUID      `gorm:"type:uuid"`
	Domain           string          `gorm:"type:varchar(255);uniqueIndex:uq_tls_certificates_domain"`
	FolderName       *string         `gorm:"type:varchar(255)"`
	Status           *string         `gorm:"type:varchar(32)"`
	Email            *string         `gorm:"type:varchar(255)"`
	Certificate      *string         `gorm:"type:text"`
	PrivateKey       *string         `gorm:"type:text"`
	Sans             *datatypes.JSON `gorm:"type:jsonb"`
	Issuer           *string         `gorm:"type:varchar(255)"`
	NotBefore        *time.Time      `gorm:"type:timestamp"`
	NotAfter         *time.Time      `gorm:"type:timestamp"`
	IsValid          *bool           `gorm:"type:boolean"`
	DaysRemaining    *int            `gorm:"type:integer"`
	SansChanged      bool            `gorm:"type:boolean"`
	LastErrorMessage *string         `gorm:"type:text"`
	LastErrorTime    *time.Time      `gorm:"type:timestamp"`
	CreatedAt        time.Time       `gorm:"autoCreateTime"`
	UpdatedAt        time.Time       `gorm:"autoUpdateTime"`
}

func (TlsCertificate) TableName() string { return "vault.tls_certificates" }

func (m *TlsCertificate) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TlsCertificateCols = struct {
	ID, AccountID, ProfileID, Domain, FolderName, Status, Email,
	Certificate, PrivateKey, Sans, Issuer, NotBefore, NotAfter, IsValid,
	DaysRemaining, SansChanged, LastErrorMessage, LastErrorTime, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	ProfileID:        "profile_id",
	Domain:           "domain",
	FolderName:       "folder_name",
	Status:           "status",
	Email:            "email",
	Certificate:      "certificate",
	PrivateKey:       "private_key",
	Sans:             "sans",
	Issuer:           "issuer",
	NotBefore:        "not_before",
	NotAfter:         "not_after",
	IsValid:          "is_valid",
	DaysRemaining:    "days_remaining",
	SansChanged:      "sans_changed",
	LastErrorMessage: "last_error_message",
	LastErrorTime:    "last_error_time",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

const (
	TlsCertificatePk       = "tls_certificates_pkey"
	TlsCertificateUkDomain = "uq_tls_certificates_domain"
)
