// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type SystemState struct {
	ID                    uuid.UUID       `gorm:"type:uuid;primaryKey"`
	Initialized           bool            `gorm:"type:boolean"`
	InitializedAt         *time.Time      `gorm:"type:timestamp"`
	InitializationVersion *string         `gorm:"type:varchar(50)"`
	ResetCount            int             `gorm:"type:integer"`
	Metadata              *datatypes.JSON `gorm:"type:jsonb"`
	CreatedAt             time.Time       `gorm:"autoCreateTime"`
	UpdatedAt             time.Time       `gorm:"autoUpdateTime"`
}

func (SystemState) TableName() string { return "system.system_state" }

func (m *SystemState) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var SystemStateCols = struct {
	ID, Initialized, InitializedAt, InitializationVersion, ResetCount, Metadata, CreatedAt,
	UpdatedAt string
}{
	ID:                    "id",
	Initialized:           "initialized",
	InitializedAt:         "initialized_at",
	InitializationVersion: "initialization_version",
	ResetCount:            "reset_count",
	Metadata:              "metadata",
	CreatedAt:             "created_at",
	UpdatedAt:             "updated_at",
}

const (
	SystemStatePk = "system_state_pkey"
)
