package render

import (
	"fmt"
	"strings"

	"nfxvault/databases/cmd/schemagen/introspect"
)

// Enums renders the single enums file for a schema, matching
// databases/templates/gen_enums.tmpl. Returns ("", false) when the schema has
// no enums (no file is emitted, as in the original).
func Enums(schema *introspect.Schema) (string, bool) {
	if len(schema.Enums) == 0 {
		return "", false
	}
	var b strings.Builder
	b.WriteString("// Code generated by gen-enums. DO NOT EDIT.\n\n")
	b.WriteString("package enums\n\n")
	for _, e := range schema.Enums {
		goType := EnumGoType(schema.Name, e.Name)
		fmt.Fprintf(&b, "type %s string\n\n", goType)
		b.WriteString("const (\n")
		for _, v := range e.Values {
			fmt.Fprintf(&b, "\t%s%s %s = %q\n", goType, Title(v), goType, v)
		}
		b.WriteString(")\n\n")
	}
	return b.String(), true
}
