package render

import (
	"fmt"
	"sort"
	"strings"
)

// importFor maps a package selector prefix found in generated code to its
// import path. goimports finalizes grouping/pruning afterwards; this pre-seed
// avoids relying on goimports guessing ambiguous names (e.g. "uuid").
var importFor = map[string]string{
	"uuid.":      "github.com/google/uuid",
	"time.":      "time",
	"datatypes.": "gorm.io/datatypes",
	"gorm.":      "gorm.io/gorm",
	"enums.":     "nfxvault/enums",
	"enumx.":     "nfxvault/pkgs/enumx",
}

// assembleFile prepends the generated-code header, package clause and a
// computed import block to body. kind is "models" or "views".
func assembleFile(kind, body string) string {
	pkg := kind // package name matches the kind ("models" / "views")

	var paths []string
	for sel, path := range importFor {
		if strings.Contains(body, sel) {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen-%s. DO NOT EDIT.\n", kind)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	if len(paths) > 0 {
		b.WriteString("import (\n")
		for _, p := range paths {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body)
	return b.String()
}
